---
common_cli_packages:
  - git
  - git-lfs
  - curl
  - wget
  - vim
  - htop
  - jq
  - tree
  - tmux
  - fzf
  - unzip
  - zip
  - nano
  - bind-utils
  
common_gui_packages:
  - evince
  - libreoffice

flatpak_packages:
  - org.kde.krita
  - org.kde.okular
  - org.keepassxc.KeePassXC

git_repositories: []