---
- name: cpp - compiler
  become: true
  package: name={{ item }} state=present
  with_items:
    - clang
    - gcc
- name: cpp - build tools
  become: true
  package: name={{ item }} state=present
  with_items:
    - make
    - cmake
