---
- name: Zsh - install zsh, fonts, and dependencies
  become: true
  ansible.builtin.package:
    name:
      - curl
      - zsh
      - powerline
      - powerline-fonts
      - fira-code-fonts
    state: present