---
- name: zsh - install zsh, fonts, and dependencies
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - zsh
    - powerline
    - powerline-fonts
    - fira-code-fonts