- name: Common - include update tasks
  ansible.builtin.include_tasks: update.yml
- name: Common - include tools tasks
  ansible.builtin.include_tasks: tools.yml
- name: Common - include chrome tasks
  ansible.builtin.include_tasks: chrome.yml
- name: Common - include development tasks
  ansible.builtin.include_tasks: development.yml
