---
- name: Ruby - install packages
  become: true
  ansible.builtin.dnf:
    name: "{{ ruby_packages }}"
    state: present

- name: Ruby - configure global gemrc
  become: true
  ansible.builtin.copy:
    dest: /etc/gemrc
    content: |
      install: --no-document
      update: --no-document
    mode: '0644'