---
- name: ruby - basic install
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  become: true
  loop:
    - ruby
    - ruby-devel
- name: ruby - dependencies for native extensions on Red Hat
  become: true
  ansible.builtin.dnf:
    name=redhat-rpm-config  state=latest
  when:
    ansible_os_family == "RedHat"
- name: ruby - installation of default gems
  become: true
  community.general.gem:
    name: "{{ item }}"
    state: present
  loop:
    - bundler
    - rake
    - rspec
